language: node_js
node_js:
  - "8"
  - "10"

before_install:
  - npm install codecov -g

after_success:
  - npm run coverage | codecov

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  skip_cleanup: true
