language: node_js
node_js:
  - '10'
  - '12'

before_install:
  - npm install codecov -g

after_success:
  - npm run test:coverage | codecov

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  on:
    tags: true
  skip_cleanup: true
