dist: trusty
sudo: false

language: node_js
node_js: v8

before_install:
- npm install codecov -g

after_success:
- codecov

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
